# .travis.yml
language: go

# needed for the docker pipe
services:
  - docker

# safelist
branches:
  only:
    - master

after_success:
  # docker login is required if you want to push docker images.
  # DOCKER_PASSWORD should be a secret in your .travis.yml configuration.
  - test -n "$TRAVIS_TAG" && docker login -u=sochisic -p="$DOCKER_PASSWORD"
  - test -n "$TRAVIS_TAG" && docker build -t sochisic/play-with-lefthook .
  # - docker tag "$TRAVIS_TAG" sochisic/play-with-lefthook:latest
  - test -n "$TRAVIS_TAG" && docker push sochisic/play-with-lefthook
# snapcraft login is required if you want to push snapcraft packages to the
# store.
# You'll need to run `snapcraft export-login snap.login` and
# `travis encrypt-file snap.login --add` to add the key to the travis
# environment.
# - test -n "$TRAVIS_TAG" && snapcraft login --with snap.login

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
