# .travis.yml
language: go

# needed for the docker pipe
services:
  - docker

# safelist regexp for check branches like: v1.3
branches:
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

after_success:
  # docker login is required if you want to push docker images.
  # DOCKER_PASSWORD should be a secret in your .travis.yml configuration.
  - test -n "$TRAVIS_TAG" && docker login -u=sochisic -p="$DOCKER_PASSWORD"
  - test -n "$TRAVIS_TAG" && docker build -t sochisic/play-with-lefthook:"$TRAVIS_TAG" -t sochisic/play-with-lefthook .
  # - test -n "$TRAVIS_TAG" && docker tag "$TRAVIS_TAG" sochisic/play-with-lefthook:latest
  - test -n "$TRAVIS_TAG" && docker push sochisic/play-with-lefthook

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

# after_deploy:
#   - script:
