language: go
services:
  - docker
branches:
  only:
    - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
after_success:
  - test -n "$TRAVIS_TAG" && docker login -u=sochisic -p="$DOCKER_PASSWORD"
  - test -n "$TRAVIS_TAG" && docker build -t sochisic/play-with-lefthook:"$TRAVIS_TAG"
    -t sochisic/play-with-lefthook .
  - test -n "$TRAVIS_TAG" && docker push sochisic/play-with-lefthook
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
after_deploy: bash scripts/deploy.sh
before_install:
  - sudo apt-get install sshpass
  - openssl aes-256-cbc -K $encrypted_065220e2d887_key -iv $encrypted_065220e2d887_iv
    -in scripts/aws-bot-vps.pem.enc -out ~/.ssh/id_rsa -md md5 && chmod 400 ~/.ssh/id_rsa
  - eval "$(ssh-agent)"
  - sshpass -p "" ssh-add ~/.ssh/id_rsa
